# Generated by Django 2.2.6 on 2019-10-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lesson.Lesson')),
            ],
        ),
    ]
